services:
#    doc.example:
#        class: DocBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    doc.chaines:
        class: DocBundle\Services\DocChaines
        arguments: ["@service_id", "plain_value", "%parameter%"]


