<?php

namespace DocBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormatType extends AbstractType
{


    private $formats;

    /**
     * @return mixed
     */
    public function getFormats()
    {
        return $this->formats;
    }

    /**
     * @param mixed $formats
     */
    public function addFormats($formats)
    {
        dump($formats);
        exit();
        $this->formats[] = $formats;
    }

    public function __construct()
    {
        $this->formats = array();

    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {


    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'label' => 'Format du livre',
            'choices' => $this->formats,
            'expanded' => false,
            'multiple' => false

        ]);
    }

    public function getBlockPrefix()
    {
        return 'doc_bundle_format_type';
    }

    /**
     * @return null|string
     *
     * @TODO permet de récuper les methodes parents
     *
     */

    public function getParent()
    {
        return ChoiceType::class; // TODO: Change the autogenerated stub
    }


}
