<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0dqtl9z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0dqtl9z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0dqtl9z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0dqtl9z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0dqtl9z\appDevDebugProjectContainer(array(
    'container.build_hash' => '0dqtl9z',
    'container.build_id' => '4e4d5966',
    'container.build_time' => 1539960000,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0dqtl9z');
