<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ndumwa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ndumwa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5ndumwa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5ndumwa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5ndumwa\appDevDebugProjectContainer(array(
    'container.build_hash' => '5ndumwa',
    'container.build_id' => '606d1fb4',
    'container.build_time' => 1539782670,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5ndumwa');
